{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.ssh-known-hosts-manager;

  # Use the centralized and corrected parser
  parseSSHConfig = import ../../lib/parse-ssh-config.nix { inherit lib; };

  hostToIP = if cfg.sshConfigFile != null then
    parseSSHConfig (builtins.readFile cfg.sshConfigFile)
  else {};
  
  # Read host keys (pattern: {hostname}-host-ed25519.pub)
  hostKeyFiles = if cfg.keysDirectory != null then
    builtins.attrNames (
      filterAttrs (name: type: 
        type == "regular" && hasSuffix "-host-ed25519.pub" name
      ) (builtins.readDir cfg.keysDirectory)
    )
  else [];
  
  # Convert to known_hosts format with hostname,IP
  knownHostsEntries = concatMapStringsSep "\n" (file:
    let
      hostname = removeSuffix "-host-ed25519.pub" file;
      key = strings.trim (builtins.readFile (cfg.keysDirectory + "/${file}"));
      # Add IP if we have a mapping, otherwise just hostname
      hostPattern = if hostToIP ? ${hostname}
                    then "${hostname},${hostToIP.${hostname}}"
                    else hostname;
    in
    "${hostPattern} ${key}"
  ) hostKeyFiles;

in
{
  options.programs.ssh-known-hosts-manager = {
    enable = mkEnableOption "SSH known_hosts manager";

    keysDirectory = mkOption {
      type = types.nullOr types.path;
      default = null;
      example = literalExpression "./ssh-keys";
      description = ''
        Path to directory containing *-host-ed25519.pub files.
        Files should follow naming convention: {hostname}-host-ed25519.pub
      '';
    };

    sshConfigFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      example = literalExpression "./ssh-config";
      description = ''
        Path to ssh-config file to parse for Host -> Hostname (IP) mappings.
        When provided, known_hosts entries will include both hostname and IP.
      '';
    };

    outputFile = mkOption {
      type = types.str;
      default = ".ssh/known_hosts_managed";
      description = ''
        Output file path relative to home directory.
        Defaults to .ssh/known_hosts_managed (separate from user's known_hosts).
      '';
    };

    extraKnownHosts = mkOption {
      type = types.listOf types.str;
      default = [];
      description = ''
        Additional known_hosts entries to add directly.
      '';
    };
  };

  config = mkIf cfg.enable {
    # Create managed known_hosts file
    home.file."${cfg.outputFile}" = {
      text = ''
        # NixOS-managed known_hosts (read-only)
        # Auto-generated by ssh-known-hosts-manager
        ${knownHostsEntries}
        ${concatStringsSep "\n" cfg.extraKnownHosts}
      '';
    };
  };
}
